// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whbqsangwovfavuwxzau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoYnFzYW5nd292ZmF2dXd4emF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NzA4NDUsImV4cCI6MjA1MDM0Njg0NX0.Qf9if99MUzX7wUaW7beBnb17IjFvpVUcNvT1WmrsFww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);